apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-letsencrypt-companion
  name: nginx-letsencrypt-companion
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-letsencrypt-companion
    spec:
      containers:
      - image: jrcs/letsencrypt-nginx-proxy-companion
        name: nginx-letsencrypt-companion
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/certs
          name: nginx-letsencrypt-companion-claim0
        - mountPath: /var/run/docker.sock
          name: nginx-letsencrypt-companion-claim1
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-letsencrypt-companion-claim0
        persistentVolumeClaim:
          claimName: nginx-letsencrypt-companion-claim0
      - name: nginx-letsencrypt-companion-claim1
        persistentVolumeClaim:
          claimName: nginx-letsencrypt-companion-claim1
          readOnly: true
status: {}
