apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-proxy
    spec:
      containers:
      - image: jwilder/nginx-proxy
        name: nginx-proxy
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/vhost.d
          name: nginx-proxy-claim0
        - mountPath: /usr/share/nginx/html
          name: nginx-proxy-claim1
        - mountPath: /tmp/docker.sock
          name: nginx-proxy-claim2
          readOnly: true
        - mountPath: /etc/nginx/certs
          name: nginx-proxy-claim3
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-proxy-claim0
        persistentVolumeClaim:
          claimName: nginx-proxy-claim0
      - name: nginx-proxy-claim1
        persistentVolumeClaim:
          claimName: nginx-proxy-claim1
      - name: nginx-proxy-claim2
        persistentVolumeClaim:
          claimName: nginx-proxy-claim2
          readOnly: true
      - name: nginx-proxy-claim3
        persistentVolumeClaim:
          claimName: nginx-proxy-claim3
          readOnly: true
status: {}
